# Generated by Django 4.0.1 on 2022-01-06 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myshop_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.CharField(default='', max_length=50),
        ),
    ]
