# Generated by Django 4.0.1 on 2022-01-08 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myshop_app', '0003_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.CharField(default='', max_length=50),
        ),
    ]
